# Script to test out downsampling PSFs
### *11/04/25*

Thinking of a clever way to do this now. Ander suggested interpolation

In [ ]:
import os
import sys

from glob      import glob
from functools import reduce


sys.path.append("/gluster/data/next/software/IC_311024/")
sys.path.append(os.path.expanduser('~/code/eol_hsrl_python'))
#sys.path.append("/home/e78368jw/Documents/NEXT_CODE/next_misc/")
os.environ['ICTDIR']='/gluster/data/next/software/IC_311024/'

from invisible_cities.io.dst_io import load_dst
from invisible_cities.io.dst_io import df_writer

import numpy  as np
import pandas as pd
import tables as tb


def load_psf(file):
    return load_dst(file, "PSF", "PSFs")

In [ ]:
one_mm_psf = load_psf('/gluster/data/next/files/TOPOLOGY_John/N100_data/14914/prod_psf/eutropia/merged_psfs/final_psf.psf')

In [ ]:
display(one_mm_psf)
print(one_mm_psf.xr.unique())

xr     yr  zr    x    y      z    factor   nevt
0       -499.5 -499.5   0  0.0  0.0   75.0  0.000000   69.0
1       -499.5 -499.5   0  0.0  0.0  175.0  0.000000   64.0
2       -499.5 -499.5   0  0.0  0.0  275.0  0.000006   98.0
3       -499.5 -499.5   0  0.0  0.0  375.0  0.000000  123.0
4       -499.5 -499.5   0  0.0  0.0  475.0  0.000033  108.0
...        ...    ...  ..  ...  ...    ...       ...    ...
9999995  499.5  499.5   0  0.0  0.0  575.0  0.000047  178.0
9999996  499.5  499.5   0  0.0  0.0  675.0  0.000066  192.0
9999997  499.5  499.5   0  0.0  0.0  775.0  0.000051  196.0
9999998  499.5  499.5   0  0.0  0.0  875.0  0.000000  223.0
9999999  499.5  499.5   0  0.0  0.0  975.0  0.000082  242.0

[10000000 rows x 8 columns]

[-499.5 -498.5 -497.5 -496.5 -495.5 -494.5 -493.5 -492.5 -491.5 -490.5
 -489.5 -488.5 -487.5 -486.5 -485.5 -484.5 -483.5 -482.5 -481.5 -480.5
 -479.5 -478.5 -477.5 -476.5 -475.5 -474.5 -473.5 -472.5 -471.5 -470.5
 -469.5 -468.5 -467.5 -466.5 -465.5 -464.5 -463.5 -462.5 -461.5 -460.5
 -459.5 -458.5 -457.5 -456.5 -455.5 -454.5 -453.5 -452.5 -451.5 -450.5
 -449.5 -448.5 -447.5 -446.5 -445.5 -444.5 -443.5 -442.5 -441.5 -440.5
 -439.5 -438.5 -437.5 -436.5 -435.5 -434.5 -433.5 -432.5 -431.5 -430.5
 -429.5 -428.5 -427.5 -426.5 -425.5 -424.5 -423.5 -422.5 -421.5 -420.5
 -419.5 -418.5 -417.5 -416.5 -415.5 -414.5 -413.5 -412.5 -411.5 -410.5
 -409.5 -408.5 -407.5 -406.5 -405.5 -404.5 -403.5 -402.5 -401.5 -400.5
 -399.5 -398.5 -397.5 -396.5 -395.5 -394.5 -393.5 -392.5 -391.5 -390.5
 -389.5 -388.5 -387.5 -386.5 -385.5 -384.5 -383.5 -382.5 -381.5 -380.5
 -379.5 -378.5 -377.5 -376.5 -375.5 -374.5 -373.5 -372.5 -371.5 -370.5
 -369.5 -368.5 -367.5 -366.5 -365.5 -364.5 -363.5 -362.5 -361.5 -360.5
 -359.

In [ ]:
rebin = 5
display((one_mm_psf.xr // rebin) * rebin)

0         -500.0
1         -500.0
2         -500.0
3         -500.0
4         -500.0
           ...  
9999995    495.0
9999996    495.0
9999997    495.0
9999998    495.0
9999999    495.0
Name: xr, Length: 10000000, dtype: float64

In [ ]:
x = np.array([0,1,2,3,4,5,6,7,8,9,10])
rebin = 2
display((x // 2)*2)

array([ 0,  0,  2,  2,  4,  4,  6,  6,  8,  8, 10])

In [ ]:
for i, j in one_mm_psf.groupby(['xr', 'yr', 'z']):
    print(i)
    display(j)
    break

(-499.5, -499.5, 75.0)


xr     yr  zr    x    y     z  factor  nevt
0 -499.5 -499.5   0  0.0  0.0  75.0     0.0  69.0

In [ ]:
# apply rebinning
#rebin = 5

#one_mm_psf['xr'] = (one_mm_psf['xr'] // rebin) * rebin
#one_mm_psf['yr'] = (one_mm_psf['yr'] // rebin) * rebin
#display(one_mm_psf)

xr     yr  zr    x    y      z    factor   nevt
0       -500.0 -500.0   0  0.0  0.0   75.0  0.000000   69.0
1       -500.0 -500.0   0  0.0  0.0  175.0  0.000000   64.0
2       -500.0 -500.0   0  0.0  0.0  275.0  0.000006   98.0
3       -500.0 -500.0   0  0.0  0.0  375.0  0.000000  123.0
4       -500.0 -500.0   0  0.0  0.0  475.0  0.000033  108.0
...        ...    ...  ..  ...  ...    ...       ...    ...
9999995  495.0  495.0   0  0.0  0.0  575.0  0.000047  178.0
9999996  495.0  495.0   0  0.0  0.0  675.0  0.000066  192.0
9999997  495.0  495.0   0  0.0  0.0  775.0  0.000051  196.0
9999998  495.0  495.0   0  0.0  0.0  875.0  0.000000  223.0
9999999  495.0  495.0   0  0.0  0.0  975.0  0.000082  242.0

[10000000 rows x 8 columns]

In [ ]:
display(one_mm_psf.zr.unique())
display(one_mm_psf.x.unique())
display(one_mm_psf.y.unique())

array([0])

array([0.])

array([0.])

In [ ]:
# apply rebinning
rebin = 5

one_mm_psf['xr'] = (one_mm_psf['xr'] // rebin) * rebin
one_mm_psf['yr'] = (one_mm_psf['yr'] // rebin) * rebin

one_mm_psf_downsampled = one_mm_psf.groupby(['xr', 'yr', 'zr', 'x', 'y', 'z']).agg({
                                                      'factor' : 'mean',
                                                      'nevt'   : 'sum'}).reset_index()
display(one_mm_psf_downsampled)

xr     yr  zr    x    y      z    factor    nevt
0      -500.0 -500.0   0  0.0  0.0   75.0  0.000030  1760.0
1      -500.0 -500.0   0  0.0  0.0  175.0  0.000027  2084.0
2      -500.0 -500.0   0  0.0  0.0  275.0  0.000008  2548.0
3      -500.0 -500.0   0  0.0  0.0  375.0  0.000008  2769.0
4      -500.0 -500.0   0  0.0  0.0  475.0  0.000025  3012.0
...       ...    ...  ..  ...  ...    ...       ...     ...
399995  495.0  495.0   0  0.0  0.0  575.0  0.000015  4236.0
399996  495.0  495.0   0  0.0  0.0  675.0  0.000044  4637.0
399997  495.0  495.0   0  0.0  0.0  775.0  0.000040  4980.0
399998  495.0  495.0   0  0.0  0.0  875.0  0.000034  5274.0
399999  495.0  495.0   0  0.0  0.0  975.0  0.000054  5664.0

[400000 rows x 8 columns]

# Compare to 5mm PSF

In [ ]:
five_mm_psf = load_psf('/gluster/data/next/files/TOPOLOGY_John/N100_data/14914/prod_psf/eutropia/merged_psfs/5mm/final_psf_5mm.psf')

In [ ]:
import functions as func


In [ ]:
# calculate Delta r
rr_5mm = func.rr_process(five_mm_psf)
rr_5mm_ds = func.rr_process(one_mm_psf_downsampled)

NameError: name 'one_mm_psf_downsampled' is not defined