### toy to test what beersheba does to the psf

In [1]:
import sys,os,os.path
sys.path.append("../../../")   # cite IC from parent directory
                            # NOTE if you can't import IC stuff, its because of the
                            # above line
#sys.path.append(os.path.expanduser('~/code/eol_hsrl_python'))
os.environ['ICTDIR']='/home/e78368jw/Documents/NEXT_CODE/IC'

import os
import glob
import numpy  as np
import pandas as pd
import tables as tb
import matplotlib.pyplot as plt

from IC.invisible_cities.reco.psf_functions    import create_psf
from IC.invisible_cities.reco.psf_functions    import hdst_psf_processing
from IC.invisible_cities.reco.psf_functions    import add_empty_sensors_and_normalize_q
from IC.invisible_cities.reco.psf_functions    import add_variable_weighted_mean

import IC.invisible_cities.core.core_functions as     coref
import IC.invisible_cities.io  .dst_io         as     dstio

from IC.invisible_cities.database              import load_db
#from IC.invisible_cities.io      .kdst_io      import psf_writer
# he's dead jim, make psf_writer yourself

In [2]:
psf_path = 'psfs/'
psf_dataN100 = dstio.load_dst(psf_path + 'NEXT100_PSF_kr83m_5bar.h5', 'PSF', 'PSFs')

In [3]:
display(psf_dataN100)
var_name     = np.array(['xr', 'yr', 'z'])
columns = var_name[:3]
print(columns)

xr    yr  zr    x    y       z    factor   nevt
0      -39.5 -39.5   0  0.0  0.0    25.0  0.000793  109.0
1      -39.5 -39.5   0  0.0  0.0    75.0  0.000713  137.0
2      -39.5 -39.5   0  0.0  0.0   125.0  0.000715  132.0
3      -39.5 -39.5   0  0.0  0.0   175.0  0.000758  121.0
4      -39.5 -39.5   0  0.0  0.0   225.0  0.000701  108.0
...      ...   ...  ..  ...  ...     ...       ...    ...
147195  39.5  39.5   0  0.0  0.0   925.0  0.000705  116.0
147196  39.5  39.5   0  0.0  0.0   975.0  0.000844  131.0
147197  39.5  39.5   0  0.0  0.0  1025.0  0.000745  128.0
147198  39.5  39.5   0  0.0  0.0  1075.0  0.001015  142.0
147199  39.5  39.5   0  0.0  0.0  1125.0  0.000698  144.0

[147200 rows x 8 columns]

['xr' 'yr' 'z']


uses length of data (var_name[:3]) to decide how many dimensions you're going to apply the reshape to.

now to do whats done to it in beersheba

In [30]:
psf_deco      = psf_dataN100.factor.values.reshape(psf_dataN100.loc[:, columns].nunique().values)

In [17]:
print(psf_dataN100.factor.values)

[0.0007929  0.00071327 0.00071456 ... 0.00074512 0.00101535 0.00069779]


In [22]:
print(psf_dataN100.loc[:, columns].nunique().values)

[80]


In [32]:
print(psf_deco)

[[[0.0007929  0.00071327 0.00071456 ... 0.00081194 0.00076095 0.00081249]
  [0.00086252 0.00082589 0.00073339 ... 0.00098367 0.00082808 0.00067998]
  [0.00069502 0.00091758 0.00103098 ... 0.00076805 0.00094877 0.00082142]
  ...
  [0.00093203 0.00072207 0.00066054 ... 0.00093963 0.00084637 0.00080284]
  [0.00086095 0.0007625  0.00066387 ... 0.00070114 0.00080226 0.0006732 ]
  [0.00110205 0.0009487  0.00053985 ... 0.00098687 0.00086051 0.00070139]]

 [[0.00105909 0.0007622  0.00061176 ... 0.00084923 0.00079661 0.00073772]
  [0.00096103 0.00090737 0.00118018 ... 0.00084898 0.00072255 0.00084154]
  [0.00084464 0.00071475 0.00101696 ... 0.00089375 0.00097118 0.00093458]
  ...
  [0.00105796 0.00084644 0.00078267 ... 0.00080549 0.00085983 0.00088102]
  [0.00094944 0.00081842 0.00066738 ... 0.00084434 0.00074515 0.00087989]
  [0.00081903 0.00086961 0.00086085 ... 0.00095317 0.00080539 0.00072586]]

 [[0.00104618 0.00091858 0.00079675 ... 0.00131012 0.00094646 0.00074467]
  [0.00100303 0.000888

In [4]:
im_deconv = 0.5 * np.ones((62,47))

TypeError: ones() missing 1 required positional argument: 'shape'